In [4]:
from maxent_insect_dir import config
from maxent_insect_dir.raw_data_utilis import *
import pathlib
import geopandas as gpd
import rasterio.plot as rioplot # To Visualize Raster Data
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
import os

pd.options.mode.chained_assignment = None  # default='warn'

In [3]:
interim_ERA5 = config.config_interim_ERA5
interim_WorldClim = config.config_interim_WorldClim

In [7]:
interim_ERA5['insect']['Brown_Marmorated_Stink_bug']

PosixPath('/data/Maxent/data/interim/ERA5/Brown_Marmorated_Stink_bug_EDD_intermediatory.gpkg')

In [54]:
interim_ERA5

{'insect': {'Brown_Marmorated_Stink_bug': PosixPath('/data/Maxent/data/interim/ERA5/Brown_Marmorated_Stink_bug_EDD_intermediatory.gpkg'),
  'Corn_Earworm': PosixPath('/data/Maxent/data/interim/ERA5/Corn_Earworm_EDD_intermediatory.gpkg'),
  'Large_Lady_Beetle': PosixPath('/data/Maxent/data/interim/ERA5/Large_Lady_Beetle_EDD_intermediatory.gpkg'),
  'Brown_Marmorated_Stink_bug_2': PosixPath('/data/Maxent/data/interim/ERA5/Brown_Marmorated_Stink_bug_2_GBIF_intermediatory.gpkg'),
  'Root_Weevil': PosixPath('/data/Maxent/data/interim/ERA5/Root_Weevil_GBIF_intermediatory.gpkg')}}

In [9]:
safe_read_file(interim_ERA5['insect']['Brown_Marmorated_Stink_bug']).columns

Index(['objectid', 'ObsDate', 'DateEnt', 'OccStatus', 'NumCollect', 'Latitude',
       'Longitude', 'label', 'NumCollect_int', 'year', 'month', 'day_number',
       'insect_id', 'crop_code', 'crop', 'BIO01', 'BIO02', 'BIO03', 'BIO04',
       'BIO05', 'BIO06', 'BIO07', 'BIO08', 'BIO09', 'BIO10', 'BIO11', 'BIO12',
       'BIO13', 'BIO14', 'BIO15', 'BIO16', 'BIO17', 'BIO18', 'BIO19',
       'geometry'],
      dtype='object')

In [62]:
df_ = safe_read_file(config.config_raw['insect']['GBIF']['Brown_Marmorated_Stink_bug_2'])
df2_ = safe_read_file(config.config_raw['insect']['GBIF']['Root_Weevil'])

In [63]:
df_.columns, df2_.columns

(Index(['Unnamed_ 0', 'species', 'occurrence', 'latitude', 'longitude', 'day',
        'month', 'Year', 'speciesKey', 'geometry'],
       dtype='object'),
 Index(['scientific', 'locality', 'occurrence', 'latitude', 'longitude', 'day',
        'month', 'Year', 'geometry'],
       dtype='object'))

In [64]:
df_.head()

,Unnamed_ 0,species,occurrence,latitude,longitude,day,month,Year,speciesKey,geometry
0,0,Halyomorpha halys,California,34.016747,-118.287683,2014-03-13T00:00:00,13.0,2014.0,4485843.0,POINT (-118.28768 34.01675)
1,1,Halyomorpha halys,Pennsylvania,40.518756,-79.807043,2014-03-30T09:31:31,30.0,2014.0,4485843.0,POINT (-79.80704 40.51876)
2,2,Halyomorpha halys,Pennsylvania,40.018108,-77.553892,2013-09-29T12:14:00,29.0,2013.0,4485843.0,POINT (-77.55389 40.01811)
3,3,Halyomorpha halys,Ohio,41.101445,-81.441779,2013-09-20T00:00:00,20.0,2013.0,4485843.0,POINT (-81.44178 41.10144)
4,4,Halyomorpha halys,Vermont,44.016878,-73.178033,2013-10-02T00:00:00,2.0,2013.0,4485843.0,POINT (-73.17803 44.01688)

In [65]:
df2_.head()

,scientific,locality,occurrence,latitude,longitude,day,month,Year,geometry
0,"Diaprepes abbreviatus (Linnaeus""",US,Florida,26.082689,-80.237779,2023-06-13T14:26:00,13,2023,POINT (-80.23778 26.08269)
1,"Diaprepes abbreviatus (Linnaeus""",US,Florida,28.813627,-81.324068,2017-07-16T21:08:14,16,2017,POINT (-81.32407 28.81363)
2,"Diaprepes abbreviatus (Linnaeus""",US,Texas,29.755168,-95.417309,2023-06-13T14:25:09,13,2023,POINT (-95.41731 29.75517)
3,"Diaprepes abbreviatus (Linnaeus""",US,Texas,29.958864,-95.562072,2023-06-12T16:13:37,12,2023,POINT (-95.56207 29.95886)
4,"Diaprepes abbreviatus (Linnaeus""",US,Texas,29.584945,-95.031163,2023-06-11T14:35:33,11,2023,POINT (-95.03116 29.58494)

In [58]:
df_['locality'].unique()

KeyError: 'locality'

In [51]:
df_['occurrence'].unique()

array(['Florida', 'Texas', 'Isabela', 'CanÃ?Â³vanas', 'Lares',
       'California', 'Cayey', 'MayagÃ?Â¼ez', 'Naguabo', 'Hato Mayor',
       'San Juan', 'South Carolina', 'Louisiana', 'Alabama', 'Jayuya',
       'Arecibo', 'Mississippi', 'Luquillo', 'Barahona', 'Gurabo',
       'Guaynabo', 'Orocovis', 'Lajas', 'Barranquitas', 'Patillas',
       'Hatillo', 'ManatÃ?Â\xad', 'Puerto Plata', 'Caguas', 'Cidra',
       'RÃ?Â\xado Grande', 'Corozal', 'Utuado', 'Georgia', 'Naranjito',
       'Duarte', 'Aguada', 'AÃ?Â±asco', 'MarÃ?Â\xada Trinidad SÃ?Â¡nchez',
       'Villalba', 'Las Piedras', 'Adjuntas', 'Juana DÃ?Â\xadaz',
       'Aguas Buenas', 'Coamo', 'SamanÃ?Â¡', 'La Romana', 'Ciales',
       'Humacao', 'Ceiba'], dtype=object)

In [27]:
df_['locality'].unique()

array(['US', 'PR', 'DO'], dtype=object)

In [ ]:
df_['occurrence'].unique()

In [10]:
safe_read_file(interim_WorldClim['insect']['Brown_Marmorated_Stink_bug']).columns

Index(['objectid', 'ObsDate', 'DateEnt', 'OccStatus', 'NumCollect', 'Latitude',
       'Longitude', 'label', 'NumCollect_int', 'year', 'month', 'day_number',
       'insect_id_x', 'crop_code', 'crop', 'WORLDCLIM_YEARLY_AVG_BIO1',
       'WORLDCLIM_YEARLY_AVG_BIO2', 'WORLDCLIM_YEARLY_AVG_BIO3',
       'WORLDCLIM_YEARLY_AVG_BIO4', 'WORLDCLIM_YEARLY_AVG_BIO5',
       'WORLDCLIM_YEARLY_AVG_BIO6', 'WORLDCLIM_YEARLY_AVG_BIO7',
       'WORLDCLIM_YEARLY_AVG_BIO8', 'WORLDCLIM_YEARLY_AVG_BIO9',
       'WORLDCLIM_YEARLY_AVG_BIO10', 'WORLDCLIM_YEARLY_AVG_BIO11',
       'WORLDCLIM_YEARLY_AVG_BIO12', 'WORLDCLIM_YEARLY_AVG_BIO13',
       'WORLDCLIM_YEARLY_AVG_BIO14', 'WORLDCLIM_YEARLY_AVG_BIO15',
       'WORLDCLIM_YEARLY_AVG_BIO16', 'WORLDCLIM_YEARLY_AVG_BIO17',
       'WORLDCLIM_YEARLY_AVG_BIO18', 'WORLDCLIM_YEARLY_AVG_BIO19',
       'insect_id_y', 'WORLDCLIM_MONTHLY_AVG_tmax',
       'WORLDCLIM_MONTHLY_AVG_tmin', 'WORLDCLIM_MONTHLY_AVG_prec', 'geometry'],
      dtype='object')

In [112]:
temp = safe_read_file(config.config_raw['insect']['EDD']['Large_Lady_Beetle'])

/home/pc19d/anaconda3/envs/postdoc/lib/python3.12/site-packages/pyogrio/geopandas.py:261: UserWarning: More than one layer found in 'Large_Lady_Beetle - (Harmonia_Axyridis) (1995-2023).gpkg': 'PointLayer' (default), 'PolygonLayer', 'LineLayer'. Specify layer parameter to avoid this warning.
  result = read_func(

Unicode decoding error occurred while reading layer 'None' from /data/Maxent/data/raw/Species Data/Guna/EDD Maps Site/Large_Lady_Beetle - (Harmonia_Axyridis) (1995-2023).gpkg. Attempting with ISO-8859-1 encoding.

In [113]:
# Assuming temp is your DataFrame and 'Location' contains the location strings
# Split 'Location' column
split_location = temp['Location'].str.split(',', expand=True)
# Select the first and second columns (state and country)
temp['state'] = split_location[1].str.strip().str.lower().str.replace('"','')
temp['country'] = split_location[2].str.strip().str.lower().str.replace('"','')

In [114]:
temp['country'].unique()

array(['united states', 'canada'], dtype=object)